language: haskell
ghc:
  - "7.8"
  - "7.10"
install:
  - cabal install --enable-tests --enable-benchmarks --dependencies-only

script:
  - cabal configure --enable-tests --enable-benchmarks --enable-coverage --ghc-option=-DTEST
  - cabal build
  - cabal test
  - cabal bench
