language: haskell
ghc:
  - 7.6
  - 7.8
install:
  - cabal install --enable-tests --enable-benchmarks

script:
  - cabal configure --enable-tests --enable-benchmarks
  - cabal build
  - cabal test
  - cabal bench
