version: 2

defaults: &defaults
  working_directory: ~/project/UnlimitedRegisterMachine

jobs:
  test82:
    docker:
      - image: haskell:8.2
    steps:
      - checkout
      - run:
          command: cabal update
      - run:
          command: cabal sandbox init
      - run:
          command: cabal install --enable-tests --enable-benchmarks --dependencies-only
      - run:
          command: cabal configure --enable-tests --enable-benchmarks --enable-coverage --ghc-option=-DTEST
      - run:
          command: cabal build
      - run:
          command: cabal test --show-details=always
      - run:
          command: cabal bench

  test8:
    docker:
      - image: haskell:8
    steps:
      - checkout
      - run:
          command: cabal update
      - run:
          command: cabal sandbox init
      - run:
          command: cabal install --enable-tests --enable-benchmarks --dependencies-only
      - run:
          command: cabal configure --enable-tests --enable-benchmarks --enable-coverage --ghc-option=-DTEST
      - run:
          command: cabal build
      - run:
          command: cabal test --show-details=always
      - run:
          command: cabal bench

  test710:
    docker:
      - image: haskell:7.10
    steps:
      - checkout
      - run:
          command: cabal update
      - run:
          command: cabal sandbox init
      - run:
          command: cabal install --enable-tests --enable-benchmarks
      - run:
          command: cabal configure --enable-tests --enable-benchmarks
      - run:
          command: cabal build
      - run:
          command: cabal test --show-details=always
      - run:
          command: cabal bench

  test78:
    docker:
      - image: haskell:7.8
    steps:
      - checkout
      - run:
          command: cabal update
      - run:
          command: cabal sandbox init
      - run:
          command: cabal install --enable-tests --enable-benchmarks
      - run:
          command: cabal configure --enable-tests --enable-benchmarks
      - run:
          command: cabal build
      - run:
          command: cabal test --show-details=always
      - run:
          command: cabal bench

workflows:
  version: 2
  test:
    jobs:
      - test78
      - test710
      - test8
      - test82
